apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
    - port: 8086
      name: port
      targetPort: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb-container
          image: influxdb-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb
              mountPath: /var/lib/influxdb/
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: influxdb-pvc