apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
        app: mysql-yopark
spec:
    selector:
        app: mysql-yopark
    type: ClusterIP
    ports:
        - port: 3306
          name: mysql-port
          targetPort: 3306

---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
    labels:
        type: local
spec:
    storageClassName: mysql-db
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    hostPath:
        path: /var/lib/mysql/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pv-claim
spec:
    storageClassName: mysql-db
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        app: mysql-yopark
spec:
    selector:
        matchLabels:
            app: mysql-yopark
    replicas: 1
    template:
        metadata:
            labels:
                app: mysql-yopark
        spec:
            containers:
                - name: mysql-container
                  image: mysql-image
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3306
                        name: mysql-port
                  volumeMounts:
                      - name: mysql-pv
                        mountPath: /var/lib/mysql/
            volumes:
                - name: mysql-pv
                  persistentVolumeClaim:
                      claimName: mysql-pv-claim